GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/1

###

GET http://localhost:8080/api/users/1/resources

###

GET http://localhost:8080/api/users/2/resources

###

GET http://localhost:8080/api/users/1/buildings/

###

GET http://localhost:8080/api/users/2/buildings

###

GET http://localhost:8080/api/users/1/units/1

###

GET http://localhost:8080/api/users/2/units

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": 1,
  "username": "Marta",
  "password": "12384"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": 2,
  "username": "Ada",
  "password": "12384"
}

###

POST http://localhost:8080/api/users/2/buildings
Content-Type: application/json

{
  "type": "COTTAGE"
}

###

POST http://localhost:8080/api/users/1/buildings
Content-Type: application/json

{
  "type": "PIT"
}

###

POST http://localhost:8080/api/users/1/buildings
Content-Type: application/json

{
  "type": "QUARRY"
}

###

POST http://localhost:8080/api/users/1/buildings
Content-Type: application/json

{
  "type": "CAVERN"
}

###

POST http://localhost:8080/api/users/1/buildings
Content-Type: application/json

{
  "type": "CAVE"
}

###

POST http://localhost:8080/api/users/1/resources
Content-Type: application/json

{
  "id": 3,
  "type": "helo"
}

###

PUT http://localhost:8080/api/users/1/units/1
Content-Type: application/json

{
  "type": "GOBLIN",
  "amount": -100
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Ada",
  "password": "12384"
}