GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/1

###

GET http://localhost:8080/api/users/1/resources

###

GET http://localhost:8080/api/users/2/resources

###

GET http://localhost:8080/api/users/1/buildings

###

GET http://localhost:8080/api/users/2/buildings

###

GET http://localhost:8080/api/users/1/units

###

GET http://localhost:8080/api/users/2/units

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": 1,
  "username": "Marta",
  "password": "12384"
}

###

PUT http://localhost:8080/api/users/1/buildings
Content-Type: application/json

{
  "mudGatherersCottageQuantity": 1,
  "stoneQuarryQuantity": 1,
  "huntersHutQuantity": 1,
  "goblinsCavernOwnership": true,
  "orcsPitOwnership": false,
  "trollsCaveOwnership": false
}

###

PUT http://localhost:8080/api/users/1/units
Content-Type: application/json

{
  "goblinArcherQuantity": 1,
  "orcWarriorQuantity": 0,
  "uglyTrollQuantity": 0
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
"id": 2,
"username": "Ada",
"password": "12384"
}